<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Properties -->
  <xacro:property name="base_length" value="1.4"/>
  <xacro:property name="base_width" value="0.8"/>
  <xacro:property name="base_height" value="0.4"/>
  <xacro:property name="wheel_radius" value="0.2"/>
  <xacro:property name="wheel_width" value="0.1"/>
  <xacro:property name="wheel_suspension" value="0.05"/>
  <xacro:property name="wheel_spacing" value="0.02"/>
  <xacro:property name="caster_radius" value="0.07"/>

  <!-- Links -->
  <link name="base_link">
    <visual>
      <origin xyz="${base_length/4.0} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}" />
      </geometry>
      <material name="$(arg color)" />
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}" />
      </geometry>
    </collision>
    <xacro:box_inertia m="30.0" w="${base_width}" d="${base_length}" h="${base_height}"/>
  </link>

  <link name="base_footprint"/>
  <link name="imu_link"/>
  <link name="navsat_link"/>

  <xacro:if value="$(arg camera)">
    <link name="camera_link"/>
  </xacro:if>

  <xacro:wheel name="left_wheel" width="${wheel_width}" radius="${wheel_radius}" mass="1.0" color="white"/>
  <xacro:wheel name="right_wheel" width="${wheel_width}" radius="${wheel_radius}" mass="1.0" color="white"/>

  <link name="caster">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
      <material name="white" />
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
    </collision>
    <xacro:box_inertia m="5" w="${base_width}" d="${base_length}" h="${base_height}"/>
  </link>

  <!-- Joints -->
  <joint name="footprint_joint" type="fixed">
      <origin xyz="0 0 ${- base_height/2.0 - wheel_radius + wheel_suspension}" rpy="0 0 0"/>
      <parent link="base_link"/>
      <child link="base_footprint"/>
  </joint>

  <xacro:if value="$(arg camera)">
    <joint name="camera_joint" type="fixed">
      <origin xyz="${3*base_length/4.0 + 0.01} 0 ${-base_height/2.0 + 0.05}" rpy="0 0 0"/>
      <parent link="base_link"/>
      <child link="camera_link"/>
    </joint>
  </xacro:if>

  <joint name="imu_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="imu_link"/>
  </joint>

  <joint name="navsat_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="navsat_link"/>
  </joint>

  <joint name="left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel"/>
    <origin xyz="0.0 ${base_width/2.0 + wheel_width/2.0 + wheel_spacing} ${-base_height/2.0 + wheel_suspension}" rpy="0 0 0"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
  </joint>

  <joint name="right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel"/>
    <origin xyz="0.0 -${base_width/2.0 + wheel_width/2.0 + wheel_spacing} ${-base_height/2.0 + wheel_suspension}" rpy="0 0 0"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
  </joint>

  <joint name="caster_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster"/>
    <origin xyz="${base_length/2.0} 0 ${-base_height/2.0 + wheel_suspension - wheel_radius + caster_radius}" rpy="0 0 0"/>
  </joint>

</robot>